const MAPPING = {
  "America/Anchorage": "Alaska",
  "America/Boise": "Mountain Time (US & Canada)",
  "America/Cambridge_Bay": "Mountain Time (US & Canada)",
  "America/Chicago": "Central Time (US & Canada)",
  "America/Danmarkshavn": "UTC",
  "America/Dawson": "Pacific Time (US & Canada)",
  "America/Denver": "Mountain Time (US & Canada)",
  "America/Detroit": "Eastern Time (US & Canada)",
  "America/Edmonton": "Mountain Time (US & Canada)",
  "America/Havana": "Eastern Time (US & Canada)",
  "America/Indiana/Knox": "Central Time (US & Canada)",
  "America/Indiana/Petersburg": "Eastern Time (US & Canada)",
  "America/Indiana/Tell_City": "Central Time (US & Canada)",
  "America/Indiana/Vincennes": "Eastern Time (US & Canada)",
  "America/Indiana/Winamac": "Eastern Time (US & Canada)",
  "America/Inuvik": "Mountain Time (US & Canada)",
  "America/Iqaluit": "Eastern Time (US & Canada)",
  "America/Juneau": "Alaska",
  "America/Kentucky/Monticello": "Eastern Time (US & Canada)",
  "America/Los_Angeles": "Pacific Time (US & Canada)",
  "America/Louisville": "Eastern Time (US & Canada)",
  "America/Matamoros": "Central Time (US & Canada)",
  "America/Menominee": "Central Time (US & Canada)",
  "America/Montreal": "Eastern Time (US & Canada)",
  "America/Nassau": "Eastern Time (US & Canada)",
  "America/New_York": "Eastern Time (US & Canada)",
  "America/Nipigon": "Eastern Time (US & Canada)",
  "America/Nome": "Alaska",
  "America/North_Dakota/Beulah": "Central Time (US & Canada)",
  "America/North_Dakota/Center": "Central Time (US & Canada)",
  "America/North_Dakota/New_Salem": "Central Time (US & Canada)",
  "America/Ojinaga": "Mountain Time (US & Canada)",
  "America/Pangnirtung": "Eastern Time (US & Canada)",
  "America/Port-au-Prince": "Eastern Time (US & Canada)",
  "America/Rainy_River": "Central Time (US & Canada)",
  "America/Rankin_Inlet": "Central Time (US & Canada)",
  "America/Resolute": "Central Time (US & Canada)",
  "America/Sitka": "Alaska",
  "America/Thunder_Bay": "Eastern Time (US & Canada)",
  "America/Toronto": "Eastern Time (US & Canada)",
  "America/Vancouver": "Pacific Time (US & Canada)",
  "America/Whitehorse": "Pacific Time (US & Canada)",
  "America/Winnipeg": "Central Time (US & Canada)",
  "America/Yakutat": "Alaska",
  "America/Yellowknife": "Mountain Time (US & Canada)",
  CST6CDT: "Central Time (US & Canada)",
  EST5EDT: "Eastern Time (US & Canada)",
  "Etc/GMT": "UTC",
  "Etc/GMT+0": "UTC",
  "Etc/GMT+10": "Hawaii",
  "Etc/GMT-0": "UTC",
  "Etc/GMT0": "UTC",
  "Etc/Greenwich": "UTC",
  "Etc/UCT": "UTC",
  "Etc/Universal": "UTC",
  "Etc/UTC": "UTC",
  "Etc/Zulu": "UTC",
  GMT: "UTC",
  "GMT+0": "UTC",
  "GMT-0": "UTC",
  GMT0: "UTC",
  Greenwich: "UTC",
  MST7MDT: "Mountain Time (US & Canada)",
  "Pacific/Honolulu": "Hawaii",
  "Pacific/Johnston": "Hawaii",
  "Pacific/Rarotonga": "Hawaii",
  "Pacific/Tahiti": "Hawaii",
  PST8PDT: "Pacific Time (US & Canada)",
  UCT: "UTC",
  Universal: "UTC",
  "US/Alaska": "Alaska",
  "US/Aleutian": "Alaska",
  "US/Eastern": "Eastern Time (US & Canada)",
  "US/Hawaii": "Hawaii",
  "US/Michigan": "Eastern Time (US & Canada)",
  "US/Mountain": "Mountain Time (US & Canada)",
  "US/Pacific": "Pacific Time (US & Canada)",
  "US/Pacific-New": "Pacific Time (US & Canada)",
  UTC: "UTC",
  WET: "UTC",
  Zulu: "UTC",
}

/**
 * Best effort to convert IANA/other common timezone names to ActiveSupport "friendly" names
 * @param {String} zone Timezone string
 * @returns Friendly timezone string or null.
 */
export default function lookupFriendlyTimeZone(zone) {
  return MAPPING[zone] || null
}
