version: 0.2
env:
  variables:
    PRX_ECR_REGION: "us-east-1"
    PRX_ECR_REPOSITORY: "feeder.prx.org"
    PRX_ECR_CONFIG_PARAMETERS: "FeederEcrImageTag"
phases:
  build:
    commands:
      - "cd $(ls -d */|head -n 1)"
      - "docker-compose -f docker-compose-ci.yml build"
      - "docker-compose -f docker-compose-ci.yml run feeder"
  post_build:
    commands:
      - 'curl -sO "https://raw.githubusercontent.com/PRX/Infrastructure/master/ci/utility/post_build.sh" && chmod +x post_build.sh && bash ./post_build.sh'
