feeder:
  build: .
  volumes:
    - .:/app
  env_file:
    - .env
  links:
    - db
  ports:
    - "3000:3000"
  command: web
  environment:
    VIRTUAL_HOST: feeder.prx.docker
worker:
  image: feederprxorg_feeder
  volumes:
    - .:/app
  env_file:
    - .env
  links:
    - db
  command: worker
db:
  image: postgres
  env_file:
    - .env
  ports:
    - "5432:5432"
  volumes:
    - ./db/import:/docker-entrypoint-initdb.d
