version: "2"
services:
  feeder:
    build: .
    env_file:
      - env-example
    links:
      - db
    depends_on:
      - db
    command: test
    environment:
      VIRTUAL_HOST: feeder.prx.docker
      RAILS_ENV: test
  db:
    image: postgres
    env_file:
      - env-example
    expose:
      - "5432"
