version: "2"
networks:
  feeder-net:
    driver: bridge
services:
  feeder:
    image: feederprxorg_feeder
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    links:
      - db
    ports:
      - "3001:3000"
    command: web
    environment:
      VIRTUAL_HOST: feeder.prx.docker
    networks:
      - feeder-net
  worker:
    image: feederprxorg_feeder
    volumes:
      - .:/app
    env_file:
      - .env
    links:
      - db
    command: worker
    networks:
      - feeder-net
  db:
    image: postgres:16.2-alpine
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - ./db/import:/docker-entrypoint-initdb.d
    networks:
      - feeder-net
