version: "2"
networks:
  feeder-net:
    driver: bridge
services:
  feeder:
    image: feederprxorg_feeder
    build: .
    volumes:
      - .:/app
    env_file:
      - env-example
    links:
      - db
      - mysql
    depends_on:
      - db
      - mysql
    ports:
      - "3001:3000"
    command: web
    environment:
      VIRTUAL_HOST: feeder.prx.docker
      RAILS_ENV: test
      POSTGRES_HOST: db
      CMS_MYSQL_HOST: mysql
    networks:
      - feeder-net
  worker:
    image: feederprxorg_feeder
    volumes:
      - .:/app
    env_file:
      - env-example
    environment:
      VIRTUAL_HOST: feeder.prx.docker
      RAILS_ENV: test
      POSTGRES_HOST: db
      CMS_MYSQL_HOST: mysql
    links:
      - db
    command: worker
    networks:
      - feeder-net
  db:
    image: postgres:13.3-alpine
    env_file:
      - env-example
    expose:
      - "5432"
    volumes:
      - ./db/import:/docker-entrypoint-initdb.d
    networks:
      - feeder-net
  mysql:
    image: mysql/mysql-server:8.0.23
    command: mysqld --log_error_verbosity=1 --default-authentication-plugin=mysql_native_password --sql-mode=""
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cms_test
      MYSQL_ROOT_HOST: "%"
    env_file:
      - env-example
    expose:
      - "3306"
    networks:
      - feeder-net
