# Be sure to restart your server when you modify this file.
#
# This file eases your Rails 8.1 framework defaults upgrade.
#
# Uncomment each configuration one by one to switch to the new default.
# Once your application is ready to run with all new defaults, you can remove
# this file and set the `config.load_defaults` to `8.1`.
#
# Read the Guide for Upgrading Ruby on Rails for more info on each option.
# https://guides.rubyonrails.org/upgrading_ruby_on_rails.html

###
# Skips escaping HTML entities and line separators. When set to `false`, the
# JSON renderer no longer escapes these to improve performance.
#
# Example:
#   class PostsController < ApplicationController
#     def index
#       render json: { key: "\u2028\u2029<>&" }
#     end
#   end
#
# Renders `{"key":"\u2028\u2029<>&"}` with the previous default,
# but `{"key":"<>&"}` (separators emitted raw) with the config set to `false`.
#
# Applications that want to keep the escaping behavior can set the config to `true`.
#++
# DEFERRED. Changes the bytes on the wire for ~25 JSON render sites across the
# HAL API. Both forms are valid JSON and any real parser handles them, but
# podcast titles and descriptions are full of & and <, so effectively every
# response body changes. To verify: diff a few API responses before/after, and
# confirm no downstream consumer string-matches or checksums response bodies.
# Rails.configuration.action_controller.escape_json_responses = false

###
# Skips escaping LINE SEPARATOR (U+2028) and PARAGRAPH SEPARATOR (U+2029) in JSON.
#
# Historically these characters were not valid inside JavaScript literal strings but that changed in ECMAScript 2019.
# As such it's no longer a concern in modern browsers: https://caniuse.com/mdn-javascript_builtins_json_json_superset.
#++
# DEFERRED. Same family as escape_json_responses above -- flip the two together
# so there is one before/after comparison of API output rather than two.
# Rails.configuration.active_support.escape_js_separators_in_json = false

###
# Raises an error when order dependent finder methods (e.g. `#first`, `#second`) are called without `order` values
# on the relation, and the model does not have any order columns (`implicit_order_column`, `query_constraints`, or
# `primary_key`) to fall back on.
#
# The current behavior of not raising an error has been deprecated, and this configuration option will be removed in
# Rails 8.2.
#++
# ADOPTED. All 54 models with a table resolve order columns, so none can raise.
# The ClickHouse Rollups:: models look like exceptions -- no id, no PRIMARY KEY
# -- but ClickHouse reports MergeTree ORDER BY as PRI, which the adapter turns
# into a composite primary key. Verified with this on against the castlehouse
# schema. Opt-out disappears in 8.2 anyway.
Rails.configuration.active_record.raise_on_missing_required_finder_order_columns = true

###
# Controls how Rails handles path relative URL redirects.
# When set to `:raise`, Rails will raise an `ActionController::Redirecting::UnsafeRedirectError`
# for relative URLs without a leading slash, which can help prevent open redirect vulnerabilities.
#
# Example:
#   redirect_to "example.com"     # Raises UnsafeRedirectError
#   redirect_to "@attacker.com"   # Raises UnsafeRedirectError
#   redirect_to "/safe/path"      # Works correctly
#
# Applications that want to allow these redirects can set the config to `:log` (previous default)
# to only log warnings, or `:notify` to send ActiveSupport notifications.
#++
# ADOPTED. Every redirect_to in app/controllers goes through a path or url
# helper, so none produce a bare relative target. Worth taking on its own
# merits as open-redirect hardening.
Rails.configuration.action_controller.action_on_path_relative_redirect = :raise

###
# Use a Ruby parser to track dependencies between Action View templates
#++
# ADOPTED. Affects how cache-digest dependencies are discovered (real parser
# instead of regex scanning). No custom template dependency annotations here.
Rails.configuration.action_view.render_tracker = :ruby

###
# When enabled, hidden inputs generated by `form_tag`, `token_tag`, `method_tag`, and the hidden parameter fields
# included in `button_to` forms will omit the `autocomplete="off"` attribute.
#++
# ADOPTED. Only drops the attribute from Rails-generated hidden inputs. The
# `autocomplete: "off"` this app sets on form_with lives on the form element
# and is untouched.
Rails.configuration.action_view.remove_hidden_field_autocomplete = true
