app_name: feeder

subscribe:
  story:
    - create
    - update
    - delete
    - publish
    - unpublish

  series:
    - create
    - update
    - delete

  # TODO: crier be gone; remove feed entry handlers
  # feed_entry:
  #   - create
  #   - update
  #   - delete
