app_name: feeder

subscribe:
  story:
    - create
    - update
    - delete
    - publish
    - unpublish

  series:
    - create
    - update
    - delete

  feed_entry:
    - create
    - update
    - delete
