app_name: feeder
queue_name_prefix: <%= ENV['ANNOUNCE_RESOURCE_PREFIX'] || ENV['RAILS_ENV'] %>

subscribe:
  story:
    - create
    - update
    - delete
    - publish
    - unpublish

  series:
    - create
    - update
    - delete

  feed_entry:
    - create
    - update
    - delete
