# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DATABASE_POOL_SIZE", 5) %>
  database: <%= ENV.fetch("POSTGRES_DATABASE", "feeder-db") %>
  username: <%= ENV.fetch("POSTGRES_USER", "feeder-user") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "feeder-pass") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("POSTGRES_PORT", "5432") %>

clickhouse: &clickhouse
  adapter: clickhouse
  database: <%= ENV.fetch("CLICKHOUSE_DATABASE", "") %>
  username: <%= ENV.fetch("CLICKHOUSE_USER", "") %>
  password: <%= ENV.fetch("CLICKHOUSE_PASSWORD", "") %>
  host: <%= ENV.fetch("CLICKHOUSE_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("CLICKHOUSE_PORT", "8123") %>
  replica: true # don't try to run migrations here

development:
  primary:
    <<: *default
    database: feeder_development
  clickhouse:
    <<: *clickhouse

test:
  primary:
    <<: *default
    database: feeder_test

staging:
  primary:
    <<: *default
  clickhouse:
    <<: *clickhouse

production:
  primary:
    <<: *default
  clickhouse:
    <<: *clickhouse
