<% prefix = Rails.configuration.active_job.queue_name_prefix %>
---
# The number of allocated threads to process messages. Default 25
concurrency: <%= if ENV["WORKER_COUNT"].present? then ENV["WORKER_COUNT"] else 25 end %>

# The delay in seconds to pause a queue when it"s empty. Default 30
delay: <%= if ENV["WORKER_PAUSE"].present? then ENV["WORKER_PAUSE"] else 30 end %>

# All the queues to listen for messages
queues:
  - ["<%= prefix %>_feeder_default", 2]
  - ["<%= prefix %>_feeder_fixer_callback", 1]
  - ["<%= prefix %>_announce_feeder_series_create", 1]
  - ["<%= prefix %>_announce_feeder_series_update", 1]
  - ["<%= prefix %>_announce_feeder_series_delete", 1]
  - ["<%= prefix %>_announce_feeder_story_create", 1]
  - ["<%= prefix %>_announce_feeder_story_update", 1]
  - ["<%= prefix %>_announce_feeder_story_delete", 1]
  - ["<%= prefix %>_announce_feeder_story_publish", 1]
  - ["<%= prefix %>_announce_feeder_story_unpublish", 1]
groups:
  single_threaded:
    concurrency: 1
    queues:
      - ["<%= prefix %>_feeder_publish_podcast", 1]
