name: Lint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          bundler-cache: true
      - name: Run standard
        run: bundle exec standardrb
      - name: Run erb-lint
        run: bundle exec erblint --lint-all --format compact
